[theme]
primaryColor = "#003A70"
backgroundColor = "#0B0E14"
secondaryBackgroundColor = "#111827"
textColor = "#e5e7eb"
base = "dark"

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
